#!/bin/sh /etc/rc.common
START=90
STOP=10
USE_PROCD=1

start_service() {
        echo '------starting-----
        procd_open_instance
        procd_set_param command  /usr/bin/lora_pkt_fwd -c /etc/lora_pkt_fwd/global_conf.json
        procd_set_param respawn 5 2 0
        procd_close_instance
}

service_triggers() {
        procd_add_reload_trigger "lora_pkt_fwd"
}

reload_service() {
        stop
        start
}
